// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLO36pN_QPYdbijNq-QRDvm1o2EhQtmzw',
    appId: '1:903021608749:web:1bb3206cb553e259a45da4',
    messagingSenderId: '903021608749',
    projectId: 'gaurdian-1c568',
    authDomain: 'gaurdian-1c568.firebaseapp.com',
    storageBucket: 'gaurdian-1c568.firebasestorage.app',
    measurementId: 'G-RDERNPM32W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8De8qr_5HVXrcDg6OkzST46iGsyNF4I',
    appId: '1:903021608749:android:c0f5ff0cd8b2ad20a45da4',
    messagingSenderId: '903021608749',
    projectId: 'gaurdian-1c568',
    storageBucket: 'gaurdian-1c568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GzAfhwH3xaNcfgTmxiJko0TydP5Vt9c',
    appId: '1:903021608749:ios:793c8a33e49c7016a45da4',
    messagingSenderId: '903021608749',
    projectId: 'gaurdian-1c568',
    storageBucket: 'gaurdian-1c568.firebasestorage.app',
    iosBundleId: 'com.example.clush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GzAfhwH3xaNcfgTmxiJko0TydP5Vt9c',
    appId: '1:903021608749:ios:793c8a33e49c7016a45da4',
    messagingSenderId: '903021608749',
    projectId: 'gaurdian-1c568',
    storageBucket: 'gaurdian-1c568.firebasestorage.app',
    iosBundleId: 'com.example.clush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLO36pN_QPYdbijNq-QRDvm1o2EhQtmzw',
    appId: '1:903021608749:web:dd9346e5bd732690a45da4',
    messagingSenderId: '903021608749',
    projectId: 'gaurdian-1c568',
    authDomain: 'gaurdian-1c568.firebaseapp.com',
    storageBucket: 'gaurdian-1c568.firebasestorage.app',
    measurementId: 'G-QGS3905NEG',
  );
}
