// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:firebase_auth/firebase_auth.dart'; // Import Firebase Auth
import 'package:google_sign_in/google_sign_in.dart'; // Import Google Sign In
import 'firebase_options.dart'; // Generated by flutterfire configure (see note below)

void main() async {
  // Ensure widgets are bound before initializing Firebase
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // Note: If you haven't run 'flutterfire configure', you might need to use standard initialization
  // await Firebase.initializeApp(); 
  // Recommended:
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const AuraApp());
}

class AuraApp extends StatelessWidget {
  const AuraApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: LoginScreen(),
    );
  }
}

class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

  // Authentication Logic
  Future<User?> _signInWithGoogle(BuildContext context) async {
    try {
      // 1. Trigger the authentication flow
      final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
      
      if (googleUser == null) {
        return null; // The user canceled the sign-in
      }

      // 2. Obtain the auth details from the request
      final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

      // 3. Create a new credential
      final OAuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      // 4. Once signed in, return the UserCredential
      final UserCredential userCredential = 
          await FirebaseAuth.instance.signInWithCredential(credential);
      
      return userCredential.user;
    } catch (e) {
      print("Error signing in with Google: $e");
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Sign in failed: $e')),
      );
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFE9E6E1),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24),
          child: Column(
            children: [
              const SizedBox(height: 60),

              Image.asset(
                "assets/images/logo.png",
                height: 120,
                fit: BoxFit.contain,
              ),

              const SizedBox(height: 50),

              const Text(
                "Welcome back",
                style: TextStyle(
                  fontSize: 30,
                  fontWeight: FontWeight.bold,
                  color: Colors.black87,
                ),
              ),

              const SizedBox(height: 16),
              // ... (rest of your text widgets)
              const Spacer(), // Just using Spacer for brevity in this snippet

              /// Continue with Google
              SizedBox(
                width: double.infinity,
                height: 60,
                child: OutlinedButton.icon(
                  onPressed: () async {
                    // Call the sign-in method
                    User? user = await _signInWithGoogle(context);
                    if (user != null) {
                      print("User signed in: ${user.email}");
                      // Navigate to your next screen here, e.g.:
                      // Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => HomeScreen()));
                    }
                  },
                  icon: Image.network(
                    "https://cdn-icons-png.flaticon.com/512/2991/2991148.png",
                    height: 22,
                  ),
                  label: const Text(
                    "Continue with Google",
                    style: TextStyle(
                      fontSize: 18,
                      color: Colors.black87,
                    ),
                  ),
                  style: OutlinedButton.styleFrom(
                    backgroundColor: Colors.white,
                    side: const BorderSide(color: Colors.black12),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                ),
              ),
              
              const Spacer(),
              // ... (Bottom links)
            ],
          ),
        ),
      ),
    );
  }
}